-- DB 생성문
-- SEQUENCE 생성문 (권한을 부여했는지 확인부터 하시기 바랍니다.)
-- REPORT의 시퀀스는 한 게시판에서 조회하니 하나로 통일합니다.
--CREATE SEQUENCE SEQ_MEMBER_NO;
--CREATE SEQUENCE SEQ_ANSWER;
--CREATE SEQUENCE SEQ_BLOG;
--CREATE SEQUENCE SEQ_CATEGORY;
--CREATE SEQUENCE SEQ_ENQUIRY;
--CREATE SEQUENCE SEQ_MEMBER;
--CREATE SEQUENCE SEQ_MEMBER_IMG;
--CREATE SEQUENCE SEQ_SNS;
--CREATE SEQUENCE SEQ_POST;
--CREATE SEQUENCE SEQ_POST_IMG;
--CREATE SEQUENCE SEQ_REPORT;
--CREATE SEQUENCE SEQ_REPLY;
--CREATE SEQUENCE SEQ_TAG;
--CREATE SEQUENCE SEQ_THUMB_IMG;

-- 계정 테이블 초기화 구문
--DROP TABLE GRADE CASCADE CONSTRAINTS;
--DROP TABLE MEMBER CASCADE CONSTRAINTS;
--DROP TABLE MEMBER_IMG CASCADE CONSTRAINTS;
--DROP TABLE MEMBER_SNS CASCADE CONSTRAINTS;
--DROP TABLE MEMBER_STATUS CASCADE CONSTRAINTS;
--DROP TABLE POST_STATUS CASCADE CONSTRAINTS;
--DROP TABLE BLOG CASCADE CONSTRAINTS;
--DROP TABLE CATEGORY CASCADE CONSTRAINTS;
--DROP TABLE ENQUIRY CASCADE CONSTRAINTS;
--DROP TABLE REPLY_STATUS CASCADE CONSTRAINTS;
--DROP TABLE REPORT_STATUS CASCADE CONSTRAINTS;
--DROP TABLE SNS CASCADE CONSTRAINTS;
--DROP TABLE POST CASCADE CONSTRAINTS;
--DROP TABLE POST_IMG CASCADE CONSTRAINTS;
--DROP TABLE POST_REPORT CASCADE CONSTRAINTS;
--DROP TABLE POST_TAG CASCADE CONSTRAINTS;
--DROP TABLE REPLY CASCADE CONSTRAINTS;
--DROP TABLE REPLY_REPORT CASCADE CONSTRAINTS;
--DROP TABLE "LIKE" CASCADE CONSTRAINTS;
--DROP TABLE TAG CASCADE CONSTRAINTS;

-- 테이블 생성 구문 시작점

-- 회원 관련 엔티티

-- 회원 등급
CREATE TABLE "GRADE" (
	"GRADE_CD"	NUMBER		PRIMARY KEY,
	"GRADE_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "GRADE"."GRADE_CD" IS '회원 등급 코드';

COMMENT ON COLUMN "GRADE"."GRADE_NM" IS '회원 등급 이름';

INSERT INTO GRADE VALUES(100, '일반회원');
INSERT INTO GRADE VALUES(101, '관리자');

-- 회원 상태
CREATE TABLE "MEMBER_STATUS" (
	"STATUS_CD"	NUMBER		PRIMARY KEY,
	"STATUS_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "MEMBER_STATUS"."STATUS_CD" IS '회원 상태 코드';

COMMENT ON COLUMN "MEMBER_STATUS"."STATUS_NM" IS '회원 상태 이름';

INSERT INTO MEMBER_STATUS VALUES(200, '일반');
INSERT INTO MEMBER_STATUS VALUES(201, '탈퇴');
INSERT INTO MEMBER_STATUS VALUES(202, '정지');

-- 회원
CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		PRIMARY KEY,
	"MEMBER_PW"	VARCHAR2(1000)		NOT NULL,
	"MEMBER_NM"	VARCHAR2(15)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"INTRO"	VARCHAR2(300)		NULL,
	"VIOLATION_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"MODIFY_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS_CD"	NUMBER		REFERENCES MEMBER_STATUS,
	"GRADE_CD"	NUMBER		REFERENCES GRADE
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."INTRO" IS '한 줄 소개';

COMMENT ON COLUMN "MEMBER"."VIOLATION_COUNT" IS '경고수';

COMMENT ON COLUMN "MEMBER"."MODIFY_DT" IS '수정일';

COMMENT ON COLUMN "MEMBER"."STATUS_CD" IS '회원 상태 코드';

COMMENT ON COLUMN "MEMBER"."GRADE_CD" IS '회원 등급 코드';

-- 소셜
CREATE TABLE "SNS" (
	"SNS_NO"	NUMBER		PRIMARY KEY,
	"SNS_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "SNS"."SNS_NO" IS '소셜 번호';

COMMENT ON COLUMN "SNS"."SNS_NM" IS '소셜명';

INSERT INTO SNS VALUES(300, '이메일');
INSERT INTO SNS VALUES(301, '깃허브');
INSERT INTO SNS VALUES(302, '트위터');
INSERT INTO SNS VALUES(303, '페이스북');
INSERT INTO SNS VALUES(304, '홈페이지');

-- 회원 소셜 정보
CREATE TABLE "MEMBER_SNS" (
	"SNS_NO"	NUMBER		REFERENCES SNS NOT NULL,
	"MEMBER_NO"	NUMBER		REFERENCES MEMBER  NOT NULL,
	"MEMBER_SNS_CONTENT"	VARCHAR2(50)	NOT NULL,
    PRIMARY KEY("SNS_NO", "MEMBER_NO")
);

COMMENT ON COLUMN "MEMBER_SNS"."SNS_NO" IS '소셜 번호';

COMMENT ON COLUMN "MEMBER_SNS"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER_SNS"."MEMBER_SNS_CONTENT" IS '소셜내용';

-- 1:1 문의
CREATE TABLE "ENQUIRY" (
	"ENQUIRY_NO"	NUMBER		PRIMARY KEY,
	"ENQUIRY_TITLE"	VARCHAR2(1000)		NOT NULL,
	"ENQUIRY_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"PARENT_ENQUIRY"	NUMBER,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER	NOT NULL
);

COMMENT ON COLUMN "ENQUIRY"."ENQUIRY_NO" IS '문의 코드';

COMMENT ON COLUMN "ENQUIRY"."ENQUIRY_TITLE" IS '문의 제목';

COMMENT ON COLUMN "ENQUIRY"."ENQUIRY_CONTENT" IS '문의 내용';

COMMENT ON COLUMN "ENQUIRY"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "ENQUIRY"."MODIFY_DT" IS '수정일';

COMMENT ON COLUMN "ENQUIRY"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "ENQUIRY"."PARENT_ENQUIRY" IS '부모 문의';

CREATE TABLE "MEMBER_IMG" (
	"MEMBER_IMG_NO"	NUMBER	PRIMARY KEY,
	"MEMBER_IMG_PATH"	VARCHAR2(100)		NOT NULL,
	"MEMBER_IMG_NM"	VARCHAR2(100)		NOT NULL,
	"MEMBER_IMG_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_IMG_ORIGINAL"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NO"	NUMBER REFERENCES MEMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER_IMG"."MEMBER_IMG_NO" IS '회원 이미지 번호';

COMMENT ON COLUMN "MEMBER_IMG"."MEMBER_IMG_PATH" IS '이미지경로';

COMMENT ON COLUMN "MEMBER_IMG"."MEMBER_IMG_NM" IS '파일명';

COMMENT ON COLUMN "MEMBER_IMG"."MEMBER_IMG_DT" IS '등록일';

COMMENT ON COLUMN "MEMBER_IMG"."MEMBER_IMG_ORIGINAL" IS '원본 이미지 명';

COMMENT ON COLUMN "MEMBER_IMG"."MEMBER_NO" IS '회원번호';






-- 블로그 관련 엔티티

-- 블로그
CREATE TABLE "BLOG" (
	"BLOG_NO"	NUMBER		PRIMARY KEY,
	"BLOG_TITLE"	VARCHAR2(20)		NOT NULL,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER	NOT NULL
);

COMMENT ON COLUMN "BLOG"."BLOG_NO" IS '블로그 번호';

COMMENT ON COLUMN "BLOG"."BLOG_TITLE" IS '블로그 제목';

COMMENT ON COLUMN "BLOG"."MEMBER_NO" IS '회원번호';

-- 카테고리
CREATE TABLE "CATEGORY" (
	"CATEGORY_CD"	NUMBER		PRIMARY KEY,
	"CATEGORY_NM"	VARCHAR2(50)		NOT NULL,
	"BLOG_NO"	NUMBER	REFERENCES BLOG	NOT NULL
);

COMMENT ON COLUMN "CATEGORY"."CATEGORY_CD" IS '카테고리 코드';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NM" IS '카테고리 이름';

COMMENT ON COLUMN "CATEGORY"."BLOG_NO" IS '블로그 번호';

-- 게시글 관련 엔티티

-- 게시글 상태
CREATE TABLE "POST_STATUS" (
	"POST_STATUS_CD"	NUMBER		PRIMARY KEY,
	"POST_STATUS_NM"	VARCHAR2(20)		NOT NULL
);

INSERT INTO POST_STATUS VALUES(500, '일반');
INSERT INTO POST_STATUS VALUES(501, '삭제');
INSERT INTO POST_STATUS VALUES(502, '비공개글');
INSERT INTO POST_STATUS VALUES(503, '캐러셀');

COMMENT ON COLUMN "POST_STATUS"."POST_STATUS_CD" IS '게시글 상태 코드';

COMMENT ON COLUMN "POST_STATUS"."POST_STATUS_NM" IS '게시글 상태 이름';

-- 게시글
CREATE TABLE "POST" (
	"POST_NO"	NUMBER		PRIMARY KEY,
	"POST_TITLE"	VARCHAR2(200)		NOT NULL,
	"POST_CONTENT"	CLOB		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"REPORT_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"LIKE_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"MODIFY_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BLOG_NO"	NUMBER		REFERENCES BLOG NOT NULL,
	"CATEGORY_CD"	NUMBER	REFERENCES CATEGORY	NOT NULL,
	"POST_STATUS_CD"	NUMBER REFERENCES POST_STATUS	NOT NULL
);

COMMENT ON COLUMN "POST"."POST_NO" IS '게시글 번호';

COMMENT ON COLUMN "POST"."POST_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "POST"."POST_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "POST"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "POST"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "POST"."REPORT_COUNT" IS '신고수';

COMMENT ON COLUMN "POST"."LIKE_COUNT" IS '좋아요수';

COMMENT ON COLUMN "POST"."MODIFY_DT" IS '수정일';

COMMENT ON COLUMN "POST"."BLOG_NO" IS '블로그 번호';

COMMENT ON COLUMN "POST"."CATEGORY_CD" IS '카테고리 코드';

COMMENT ON COLUMN "POST"."POST_STATUS_CD" IS '게시글 상태 코드';


--태그
CREATE TABLE "TAG" (
	"TAG_CD"	NUMBER		PRIMARY KEY,
	"TAG_NM"	VARCHAR2(45)		NOT NULL
);

COMMENT ON COLUMN "TAG"."TAG_CD" IS '태그 코드';

COMMENT ON COLUMN "TAG"."TAG_NM" IS '태그명';


-- 게시글 태그
CREATE TABLE "POST_TAG" (
	"POST_NO"	NUMBER	REFERENCES POST	NOT NULL,
	"TAG_CD"	NUMBER	REFERENCES TAG	NOT NULL
);

COMMENT ON COLUMN "POST_TAG"."POST_NO" IS '게시글 번호';

COMMENT ON COLUMN "POST_TAG"."TAG_CD" IS '태그 번호';

-- 좋아요 엔티티
CREATE TABLE "LIKE" (
	"POST_NO"	NUMBER	REFERENCES POST	NOT NULL,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER	NOT NULL
);

COMMENT ON COLUMN "LIKE"."POST_NO" IS '게시글 번호';

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원번호';

-- 게시글 이미지
CREATE TABLE "POST_IMG" (
	"POST_IMG_NO"	NUMBER		PRIMARY KEY,
	"POST_IMG_PATH"	VARCHAR2(100)		NOT NULL,
	"POST_IMG_NM"	VARCHAR2(100)		NOT NULL,
	"POST_IMG_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"POST_IMG_ORIGINAL"	VARCHAR2(100)		NOT NULL,
	"POST_IMG_LEV"	NUMBER		NOT NULL,
    "POST_THUMB_IMG_NO" NUMBER          NULL,
    "POST_THUMB_IMG_NM" VARCHAR2(100)   NULL,
	"POST_NO"	NUMBER	REFERENCES POST	NOT NULL
);

COMMENT ON COLUMN "POST_IMG"."POST_IMG_NO" IS '게시글 이미지 번호';

COMMENT ON COLUMN "POST_IMG"."POST_IMG_PATH" IS '이미지 경로';

COMMENT ON COLUMN "POST_IMG"."POST_IMG_NM" IS '파일명';

COMMENT ON COLUMN "POST_IMG"."POST_IMG_DT" IS '등록일';

COMMENT ON COLUMN "POST_IMG"."POST_IMG_ORIGINAL" IS '원본 이미지명';

COMMENT ON COLUMN "POST_IMG"."POST_IMG_LEV" IS '이미지 레벨';

COMMENT ON COLUMN "POST_IMG"."POST_NO" IS '게시글 번호';

CREATE TABLE "STATIC_READ_COUNT" (
	"SATIC_READ_COUNT_NO"	NUMBER		PRIMARY KEY,
	"READ_COUNT_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"POST_NO"	NUMBER	REFERENCES POST	NOT NULL
);

COMMENT ON COLUMN "STATIC_READ_COUNT"."SATIC_READ_COUNT_NO" IS '조회수 통계 번호';

COMMENT ON COLUMN "STATIC_READ_COUNT"."READ_COUNT_DT" IS '조회수 증가 시간';

COMMENT ON COLUMN "STATIC_READ_COUNT"."POST_NO" IS '게시글 번호';

-- 댓글 관련 엔티티

-- 댓글 상태
CREATE TABLE "REPLY_STATUS" (
	"REPLY_STATUS_CD"	NUMBER	    PRIMARY KEY,
	"REPLY_STATUS_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REPLY_STATUS"."REPLY_STATUS_CD" IS '댓글 상태 코드';

COMMENT ON COLUMN "REPLY_STATUS"."REPLY_STATUS_NM" IS '댓글 상태 이름';

INSERT INTO REPLY_STATUS VALUES(600, '일반');
INSERT INTO REPLY_STATUS VALUES(601, '블라인드');
INSERT INTO REPLY_STATUS VALUES(602, '비밀');

-- 댓글
CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		PRIMARY KEY,
	"REPLY_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REPLY_CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPORT_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"PARENT_REPLY"	NUMBER		NULL,
	"POST_NO"	NUMBER		REFERENCES POST NOT NULL,
	"MEMBER_NO"	NUMBER		REFERENCES MEMBER NOT NULL,
	"REPLY_STATUS_CD"	NUMBER	REFERENCES REPLY_STATUS	NOT NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글 번호';

COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "REPLY"."REPLY_CREATE_DT" IS '댓글 작성일';

COMMENT ON COLUMN "REPLY"."REPORT_COUNT" IS '신고수';

COMMENT ON COLUMN "REPLY"."PARENT_REPLY" IS '부모 댓글';

COMMENT ON COLUMN "REPLY"."POST_NO" IS '게시글 번호';

COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "REPLY"."REPLY_STATUS_CD" IS '댓글 상태 코드';

COMMIT;

-- 신고 관련 엔티티 (게시글 테이블, 댓글 테이블이 있어야 생성가능하기에 아래로 둠)

-- 신고 상태
CREATE TABLE "REPORT_STATUS" (
	"REPORT_STATUS_CD"	NUMBER		PRIMARY KEY,
	"REPORT_STATUS_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REPORT_STATUS"."REPORT_STATUS_CD" IS '신고 상태 코드';

COMMENT ON COLUMN "REPORT_STATUS"."REPORT_STATUS_NM" IS '신고 상태명';

INSERT INTO REPORT_STATUS VALUES(400, '음란성');
INSERT INTO REPORT_STATUS VALUES(401, '홍보성');
INSERT INTO REPORT_STATUS VALUES(402, '기타');

-- 게시글 신고
CREATE TABLE "POST_REPORT" (
	"REPORT_NO"	NUMBER		PRIMARY KEY,
	"REPORT_CONTENT"	VARCHAR2(3000)		NOT NULL,
    "REPORT_TYPE"	VARCHAR2(20) DEFAULT '게시글'	NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"POST_NO"	NUMBER	REFERENCES POST	NOT NULL,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER	NOT NULL,
	"REPORT_STATUS_CD"	NUMBER REFERENCES REPORT_STATUS	NOT NULL
);

COMMENT ON COLUMN "POST_REPORT"."REPORT_NO" IS '신고 번호';

COMMENT ON COLUMN "POST_REPORT"."REPORT_CONTENT" IS '신고 내용';

COMMENT ON COLUMN "POST_REPORT"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "POST_REPORT"."POST_NO" IS '게시글 번호';

COMMENT ON COLUMN "POST_REPORT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "POST_REPORT"."REPORT_STATUS_CD" IS '신고 상태 코드';

COMMENT ON COLUMN "POST_REPORT"."REPORT_TYPE" IS '신고 유형';

-- 댓글 신고
CREATE TABLE "REPLY_REPORT" (
	"REPORT_NO"	NUMBER PRIMARY KEY,
	"REPORT_CONTENT"	VARCHAR2(3000)		NOT NULL,
    "REPORT_TYPE"	VARCHAR2(20) DEFAULT '댓글'	NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPLY_NO"	NUMBER	REFERENCES REPLY	NOT NULL,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER	NOT NULL,
	"REPORT_STATUS_CD"	NUMBER REFERENCES REPORT_STATUS		NOT NULL
);

COMMENT ON COLUMN "REPLY_REPORT"."REPORT_NO" IS '신고 번호';

COMMENT ON COLUMN "REPLY_REPORT"."REPORT_CONTENT" IS '신고 내용';

COMMENT ON COLUMN "REPLY_REPORT"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "REPLY_REPORT"."REPLY_NO" IS '댓글 번호';

COMMENT ON COLUMN "REPLY_REPORT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "REPLY_REPORT"."REPORT_STATUS_CD" IS '신고 상태 코드';

COMMENT ON COLUMN "REPLY_REPORT"."REPORT_TYPE" IS '신고 유형';

COMMIT;



-- 회원가입 샘플
INSERT INTO MEMBER VALUES( SEQ_MEMBER.NEXTVAL, '1234', '테스터', 'joo@naver.com', DEFAULT, NULL, DEFAULT, DEFAULT, NULL,NULL);
-- 블로그 샘플
INSERT INTO BLOG VALUES( SEQ_BLOG.NEXTVAL, 'name', 1);
-- 포스트 샘플 데이터 생성
INSERT INTO POST VALUES(SEQ_POST.NEXTVAL, '안녕하세요', '이건 <br> 내용', DEFAULT, DEFAULT, DEFAULT, DEFUALT,DEFAULT, 1);  