
-- 샘플 테이블 생성

-- 게시글 상태
CREATE TABLE POST_STATUS(
    POST_STATUS_CD NUMBER PRIMARY KEY CHECK( POST_STATUS_CD IN (500, 501, 502, 503, 504, 505)),
    POST_STATUS_NM VARCHAR(20) NOT NULL
);

-- 댓글 상태
CREATE TABLE REPLY_STATUS(
    REPLY_STATUS_CD NUMBER PRIMARY KEY CHECK( REPLY_STATUS_CD IN (600, 601, 602, 603)),
    REPLY_STATUS_NM VARCHAR(20) NOT NULL
);

CREATE TABLE BLOG(
    BLOG_NO NUMBER PRIMARY KEY,
    BLOG_TITLE VARCHAR2(20) NOT NULL,
    MEMBER_NO NUMBER NOT NULL
);

-- 카테고리
CREATE TABLE CATEGORY(
    CATEGORY_CD NUMBER PRIMARY KEY,
    CATEGORY_NM VARCHAR2(50),
    BLOG_NO NUMBER REFERENCES BLOG
);

-- 게시글
CREATE TABLE POST(
    POST_NO NUMBER PRIMARY KEY,
    POST_TITLE VARCHAR2(200) NOT NULL,
    POST_CONTENT CLOB NOT NULL,
    CREATE_DT DATE DEFAULT SYSDATE NOT NULL,
    READ_COUNT NUMBER DEFAULT 0 NOT NULL,
    REPORT_COUNT NUMBER DEFAULT 0 NOT NULL,
    LIKE_COUNT NUMBER DEFAULT 0 NOT NULL,
    MODIFY_DT DATE DEFAULT SYSDATE NOT NULL,
    BLOG_NO NUMBER REFERENCES BLOG NOT NULL,
    CATEGORY_CD NUMBER REFERENCES CATEGORY,
    POST_STATUS_CD NUMBER REFERENCES POST_STATUS
);

-- 게시글 이미지
CREATE TABLE POST_IMG(
    POST_IMG_NO NUMBER PRIMARY KEY,
    POST_IMG_PATH VARCHAR2(100) NOT NULL,
    POST_IMG_NM VARCHAR2(100) NOT NULL,
    POST_IMG_ORIGINAL VARCHAR2(100) NOT NULL,
    POST_IMG_DT DATE DEFAULT SYSDATE NOT NULL,
    POST_IMG_LEVEL NUMBER NOT NULL,
    POST_NO NUMBER REFERENCES POST
);
    

-- 댓글
CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(1000) NOT NULL,
    REPLY_CREATE_DT DATE DEFAULT SYSDATE NOT NULL,
    REPORT_COUNT NUMBER DEFAULT 0 NOT NULL,
    PARENT_REPLY NUMBER,
    POST_NO NUMBER REFERENCES POST NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    REPLY_STATUS_CD NUMBER REFERENCES REPLY_STATUS NOT NULL
);

CREATE SEQUENCE SEQ_REPLY_NO;
CREATE SEQUENCE SEQ_POST_NO;
CREATE SEQUENCE SEQ_POST_IMG_NO;
CREATE SEQUENCE SEQ_CATEGORY_NO;
--------------------------------------------------------------------------------

-- 샘플 블로그 삽입
INSERT INTO BLOG VALUES(
    1, '첫번째 블로그', 1);

INSERT INTO BLOG VALUES(
    2, '파워블로거', 2);
    
INSERT INTO BLOG VALUES(
3, 'sample', 3);

COMMIT;

-- 샘플 카테고리 삽입
INSERT INTO CATEGORY VALUES(
    SEQ_CATEGORY_NO.NEXTVAL, '개발공부', 1);
    
INSERT INTO CATEGORY VALUES(
    SEQ_CATEGORY_NO.NEXTVAL, 'IT 상식', 1);

INSERT INTO CATEGORY VALUES(
    SEQ_CATEGORY_NO.NEXTVAL, '맛집', 2);

INSERT INTO CATEGORY VALUES(
    SEQ_CATEGORY_NO.NEXTVAL, '여행', 2);

-- 게시글 상태 코드 삽입
INSERT INTO POST_STATUS VALUES(
    500, '일반');
INSERT INTO POST_STATUS VALUES(
    501, '삭제');
INSERT INTO POST_STATUS VALUES(
    502, '정지');
INSERT INTO POST_STATUS VALUES(
    503, '비밀글');
INSERT INTO POST_STATUS VALUES(
    504, '임시글');
INSERT INTO POST_STATUS VALUES(
    505, '캐러셀');
    
-- 댓글 상태
INSERT INTO REPLY_STATUS VALUES(
    600, '일반');
INSERT INTO REPLY_STATUS VALUES(
    601, '삭제');
INSERT INTO REPLY_STATUS VALUES(
    602, '비밀');
INSERT INTO REPLY_STATUS VALUES(
    603, '블라인드');

COMMIT;
    
SELECT COUNT(*) FROM POST
		WHERE POST_STATUS_CD != 501
		AND BLOG_NO = 1;    
    

-- 게시글 샘플 데이터
BEGIN
    FOR I IN 1..200 LOOP
        
        INSERT INTO POST
        VALUES(
            SEQ_POST_NO.NEXTVAL,
            SEQ_POST_NO.CURRVAL || '번째 게시글',
            SEQ_POST_NO.CURRVAL || '번째 게시글입니다.',
            DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
            FLOOR(DBMS_RANDOM.VALUE(1,4)),
            FLOOR(DBMS_RANDOM.VALUE(1,3)),
            500 + FLOOR(DBMS_RANDOM.VALUE(0,6))
            );
    
    END LOOP;
END;
/   

COMMIT;

-- 페이지가 있는 게시글 조회
--SELECT * FROM 
--    (SELECT ROWNUM RNUM, A.* FROM(
--    SELECT * FROM V_BOARD_LIST
--    WHERE BOARD_STATUS_CD != 302
--    ORDER BY BOARD_NO DESC)A)
--    WHERE RNUM BETWEEN ? AND ?
    
SELECT  POST_NO, POST_TITLE, POST_CONTENT,
        TO_CHAR( CREATE_DT, 'YYYY-MM-DD' ) CREATE_DT,
        TO_CHAR( MODIFY_DT, 'YYYY-MM-DD' ) MODIFY_DT,
        READ_COUNT, LIKE_COUNT, BLOG_NO, BLOG_TITLE, MEMBER_NO
FROM POST
JOIN BLOG USING(BLOG_NO)
WHERE POST_STATUS_CD IN (500, 505)
ORDER BY POST_NO DESC;

SELECT COUNT(*) FROM POST
		JOIN BLOG USING(BLOG_NO)
		WHERE POST_STATUS_CD != 501
		AND BLOG_TITLE = 'sample';


-- 포스트 전체 조회 VIEW
(SELECT  POST_NO, POST_TITLE, 
            SUBSTR(POST_CONTENT, 50),
            CASE WHEN SYSDATE - CREATE_DT < 1
            THEN TO_CHAR(  CREATE_DT, 'HH24:MI'  )  
            ELSE TO_CHAR(  CREATE_DT, 'YYYY-MM-DD'  ) 
            END AS "CREATE_DT",
            READ_COUNT, REPORT_COUNT, LIKE_COUNT, BLOG.BLOG_NO, 
            BLOG_TITLE, MEMBER_NO,
            CATEGORY.CATEGORY_CD, CATEGORY_NM,
            POST.POST_STATUS_CD, POST_STATUS_NM
    FROM POST
    JOIN BLOG ON(BLOG.BLOG_NO = POST.BLOG_NO)
    JOIN CATEGORY ON(POST.CATEGORY_CD = CATEGORY.CATEGORY_CD)
    JOIN POST_STATUS ON(POST.POST_STATUS_CD = POST_STATUS.POST_STATUS_CD)
    );

-- 블로그 게시글 전체 조회(페이징)
SELECT * FROM
    (SELECT ROWNUM RNUM, A.*
    FROM(SELECT * FROM
        (SELECT  POST_NO, POST_TITLE, 
                POST_CONTENT,
                CASE WHEN SYSDATE - CREATE_DT < 1
                THEN TO_CHAR(  CREATE_DT, 'HH24:MI'  )  
                ELSE TO_CHAR(  CREATE_DT, 'YYYY-MM-DD'  ) 
                END AS "CREATE_DT",
                READ_COUNT, REPORT_COUNT, LIKE_COUNT, BLOG.BLOG_NO, 
                BLOG_TITLE, MEMBER_NO,
                CATEGORY.CATEGORY_CD, CATEGORY_NM,
                POST.POST_STATUS_CD, POST_STATUS_NM
        FROM POST
        JOIN BLOG ON(BLOG.BLOG_NO = POST.BLOG_NO)
        JOIN CATEGORY ON(POST.CATEGORY_CD = CATEGORY.CATEGORY_CD)
        JOIN POST_STATUS ON(POST.POST_STATUS_CD = POST_STATUS.POST_STATUS_CD)
        )
    WHERE POST_STATUS_CD != 501
    AND BLOG_TITLE = 'sample'
    ORDER BY POST_NO DESC) A )
WHERE RNUM BETWEEN 1 AND 10    
;
        

--JOIN MEMBER USING(MEMBER_NO)
 
    






