/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2021-12-22 07:08:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- header include -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		   <main>\r\n");
      out.write("    <!---------------------------------------------------- Swiper 캐러셀 ------------------------------------->\r\n");
      out.write("    <div class=\"swiper mySwiper\"> <!-- active 클래스 넣기 -->\r\n");
      out.write("        <div class=\"swiper-wrapper\">\r\n");
      out.write("          <div class=\"swiper-slide wrapper\">\r\n");
      out.write("          <a href=\"\">\r\n");
      out.write("              <img src=\"https://via.placeholder.com/420x250\" alt=\"\" class=\"carousel-imgbox\">\r\n");
      out.write("               <div class=\"bg\">\r\n");
      out.write("                 <p>테스트입니다</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"swiper-slide wrapper\">\r\n");
      out.write("          <a href=\"\">\r\n");
      out.write("              <img src=\"https://via.placeholder.com/420x250\" alt=\"\" class=\"carousel-imgbox\">\r\n");
      out.write("               <div class=\"bg\">\r\n");
      out.write("                 <p>테스트입니다</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"swiper-slide wrapper\">\r\n");
      out.write("          <a href=\"\">\r\n");
      out.write("              <img src=\"https://via.placeholder.com/420x250\" alt=\"\" class=\"carousel-imgbox\">\r\n");
      out.write("               <div class=\"bg\">\r\n");
      out.write("                 <p>테스트입니다</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"swiper-slide wrapper\">\r\n");
      out.write("          <a href=\"\">\r\n");
      out.write("              <img src=\"https://via.placeholder.com/420x250\" alt=\"\" class=\"carousel-imgbox\">\r\n");
      out.write("               <div class=\"bg\">\r\n");
      out.write("                 <p>테스트입니다</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"swiper-slide wrapper\">\r\n");
      out.write("          <a href=\"\">\r\n");
      out.write("              <img src=\"https://via.placeholder.com/420x250\" alt=\"\" class=\"carousel-imgbox\">\r\n");
      out.write("               <div class=\"bg\">\r\n");
      out.write("                 <p>테스트입니다</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"swiper-slide wrapper\">\r\n");
      out.write("          <a href=\"\">\r\n");
      out.write("              <img src=\"https://via.placeholder.com/420x250\" alt=\"\" class=\"carousel-imgbox\">\r\n");
      out.write("               <div class=\"bg\">\r\n");
      out.write("                 <p>테스트입니다</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("     \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"swiper-pagination\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("        <!-- --------------------------------------------캐러셀 끝------------------------------------------------------- -->\r\n");
      out.write("        <button onclick=\" location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/updatepw'\"  >비밀번호 변경</button>\r\n");
      out.write("		\r\n");
      out.write("     \r\n");
      out.write("        \r\n");
      out.write("          <section class=\"post-hr\">\r\n");
      out.write("           <hr class=\"hr\" >\r\n");
      out.write("           <span class=\"post\" >post</span>\r\n");
      out.write("           <hr class=\"hr\">\r\n");
      out.write("   \r\n");
      out.write("          </section> \r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           <nav>\r\n");
      out.write("          <!-- 태그 정렬 옵션 -->\r\n");
      out.write("          <div class=\"nav-wrap\">\r\n");
      out.write("   \r\n");
      out.write("            <div class=\"sort-menu\">\r\n");
      out.write("              <div class=\"under-line-on\">\r\n");
      out.write("                <span><svg id=\"tr-img\" stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\"  xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M16 6l2.29 2.29-4.88 4.88-4-4L2 16.59 3.41 18l6-6 4 4 6.3-6.29L22 12V6z\"></path></svg>\r\n");
      out.write("                 트랜드</span>\r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("               <div class=\"under-line-off\">\r\n");
      out.write("                 <span><svg id=\"tr-img2\" stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\"  xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67z\"></path></svg>\r\n");
      out.write("                   최신</span>\r\n");
      out.write("                 </div>\r\n");
      out.write("                 \r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("               <form action=\"\" id=\"date-form\" style=\"height: 30px;\">\r\n");
      out.write("                 <select name=\"\" id=\"date\">\r\n");
      out.write("                   <option value=\"\">오늘</option>\r\n");
      out.write("                   <option value=\"\">이번주</option>\r\n");
      out.write("                   <option value=\"\">이번달</option>\r\n");
      out.write("                   <option value=\"\">올해</option>\r\n");
      out.write("                 </select>\r\n");
      out.write("               </form>\r\n");
      out.write("             </div>\r\n");
      out.write("             \r\n");
      out.write("   \r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("        </nav>\r\n");
      out.write("          \r\n");
      out.write("        <section class=\"card-bord\">\r\n");
      out.write("       \r\n");
      out.write("   \r\n");
      out.write("         <div class=\"wrapper-card\">\r\n");
      out.write("            \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("                 <a href=\"\" class=\"wrapper-a\">\r\n");
      out.write("   \r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"card\">\r\n");
      out.write("                         \r\n");
      out.write("                         <div class=\"image\"><img src=\"https://via.placeholder.com/280x150\" id=\"img-size\"></div>  \r\n");
      out.write("                         \r\n");
      out.write("                         <div class=\"title-box\">\r\n");
      out.write("                             <p  class=\"title\">제목입니다</p>\r\n");
      out.write("                         </div>  \r\n");
      out.write("                         <div class=\"user-div sub-div\">\r\n");
      out.write("                             \r\n");
      out.write("                             <span class=\"by_name\">by <b>유동훈</b></span><div class=\"likes\"><svg id=\"ht\"viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"M18 1l-6 4-6-4-6 5v7l12 10 12-10v-7z\"></path>\r\n");
      out.write("                             </svg>155</div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                         \r\n");
      out.write("                     </div>\r\n");
      out.write("                 </a>\r\n");
      out.write("             </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("   		</section>\r\n");
      out.write("       \r\n");
      out.write("       </main>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
